"""Pydantic data models for NullDay Intel.

Defines schemas for ingested raw articles, structured LLM analysis outputs,
Discord rich embed reports, and X/Twitter alerts.
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, HttpUrl


class RawArticle(BaseModel):
    """Normalized representation of a single security feed entry."""

    id: str = Field(description="Unique hash of canonical URL or title+link")
    source_id: str = Field(description="Source identifier from sources.yaml")
    source_name: str = Field(description="Human-readable source publication name")
    title: str = Field(description="Article headline")
    url: str = Field(description="Direct link to original source")
    published_at: datetime = Field(description="Normalized publication timestamp in UTC")
    summary: str = Field(default="", description="Cleaned excerpt or summary text")
    cve_candidates: List[str] = Field(
        default_factory=list, description="Extracted CVE identifiers found in text"
    )
    is_kev: bool = Field(
        default=False, description="Whether this article is a known exploited vulnerability"
    )


class IncidentItem(BaseModel):
    """Structured security incident or vulnerability brief generated by LLM."""

    title: str = Field(description="Concise, impact-focused incident headline")
    cve_id: Optional[str] = Field(
        default=None, description="Primary CVE identifier if applicable (e.g. CVE-2026-1234)"
    )
    cvss: Optional[float] = Field(
        default=None, description="CVSS v3.1/v4 base score between 0.0 and 10.0 if known"
    )
    kev_status: bool = Field(
        default=False, description="True if actively exploited in the wild (CISA KEV)"
    )
    impact_sector: str = Field(
        description="Target industry or affected technology (e.g., Healthcare, Critical Infrastructure, Enterprise VPNs, Cloud)"
    )
    estimated_damage: str = Field(
        default="Schadenssumme: Unbekannt / Nicht publiziert",
        description="Estimated ransom demand, extortion amount, data breach scale, or 'Schadenssumme: Unbekannt / Nicht publiziert'",
    )
    mitigation: str = Field(
        description="Concrete, actionable mitigation steps (e.g. patch revision, temporary IOC blocking, configuration change)"
    )
    source_url: str = Field(description="Direct URL to the original verification report")


class DiscordReport(BaseModel):
    """Structured payload for Discord executive briefing."""

    title: str = Field(
        default="NullDay Intel // Cyber Threat Briefing",
        description="Briefing header title",
    )
    summary: str = Field(
        description="Executive summary paragraph assessing the macro threat posture for the period."
    )
    strategic_analysis: str = Field(
        default="",
        description="In-depth multi-paragraph strategic threat analysis (threat actor campaigns, exploit trends, operational impact) providing a comprehensive ~5-minute executive read.",
    )
    threat_level: str = Field(
        default="ELEVATED",
        description="Current overall threat level: CRITICAL, HIGH, ELEVATED, or ROUTINE",
    )
    key_recommendations: List[str] = Field(
        default_factory=list,
        description="3 to 5 concrete strategic defensive directives for security leadership and SOC teams.",
    )
    incidents: List[IncidentItem] = Field(
        default_factory=list,
        description="List of 4 to 8 prioritized security incidents and vulnerability briefs",
    )


class XPayload(BaseModel):
    """Structured payload for X/Twitter alert and optional thread reply."""

    tweet_text: str = Field(
        description="Punchy, urgent alert strictly under 260 characters. Must highlight the #1 critical threat/CVE, impact, and 2-3 hashtags (#ThreatIntel #CyberSecurity #CVE)."
    )
    thread_reply: Optional[str] = Field(
        default=None,
        description="Optional follow-up tweet strictly under 280 characters containing mitigation guidance and link.",
    )


class CTIAnalysisResult(BaseModel):
    """Unified container produced by Google GenAI SDK in a single inference."""

    discord_report: DiscordReport
    x_payload: XPayload
